
static_sites:
  - name: applife-solutions
    buildCommand: npm install && npm run build && cp _redirects dist/
    publishPath: ./dist
    env: node
    region: frankfurt  
    
    routes:
      - path: /*
        destination: /index.html
        type: rewrite
        status: 200