
static_sites:
  - name: applifesolutions
    buildCommand: npm install && npm run build
    publishPath: ./dist
    env: node
    region: frankfurt  
    
    routes:
      - path: /*
        redirect: /index.html
